name: permissions_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  page_transition: ^2.2.1
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.3
  provider: ^6.1.4
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
  photo_manager: ^3.6.4
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/